//
//  SwiftTestCodeGeneratorTests.swift
//  CapriccioLibTests
//
//  Created by Franco on 03/09/2018.
//

import XCTest
import Foundation
import Nimble
import Gherkin
@testable import CapriccioLib

final class SwiftTestCodeGeneratorTests: XCTestCase {
    var swiftCodeGenerator: SwiftTestCodeGenerator!
    
    override func setUp() {
        super.setUp()
        swiftCodeGenerator = SwiftTestCodeGenerator()
    }
    
    override func tearDown() {
        swiftCodeGenerator = nil
        super.tearDown()
    }
    
    func testItUsesTheGeneratedClassType() {
        let scenario: Gherkin.Scenario = .simple(ScenarioSimple(name: "Scenario I want to test",
                                                        description: "",
                                                        steps:[Step(name: .given, text: "I'm in a situation"),
                                                               Step(name: .when, text: "Something happens"),
                                                               Step(name: .then, text: "Something else happens")] ))
        let feature = Feature(name: "Feature number one",
                              description: "",
                              scenarios: [scenario])
        
        let expectedResult = """
        /**
        This code is autogenerated using Capriccio 1.0.0 - https://github.com/shibapm/capriccio
        DO NOT EDIT
        */
        import XCTest
        import XCTest_Gherkin

        final class FeatureNumberOne: TestClass {
            func testScenarioIWantToTest() {
                Given("I'm in a situation")
                When("Something happens")
                Then("Something else happens")
            }
        }
        """
        
        fileGenerationCheck(feature: feature, expectedResult: expectedResult, generatedClassType: "TestClass")
    }
    
    func testItRemovesNotAllowedCaracters() {
        let scenario: Gherkin.Scenario = .simple(ScenarioSimple(name: "Scenario \\/ I want to test",
                                                        description: "",
                                                        steps:[Step(name: .given, text: "I'm in a situation"),
                                                               Step(name: .when, text: "Something happens"),
                                                               Step(name: .then, text: "Something else happens")] ))
        let feature = Feature(name: "Feature $%^& number one",
                              description: "",
                              scenarios: [scenario])
        
        let expectedResult = """
        /**
        This code is autogenerated using Capriccio 1.0.0 - https://github.com/shibapm/capriccio
        DO NOT EDIT
        */
        import XCTest
        import XCTest_Gherkin

        final class FeatureNumberOne: XCTestCase {
            func testScenarioIWantToTest() {
                Given("I'm in a situation")
                When("Something happens")
                Then("Something else happens")
            }
        }
        """
        
        fileGenerationCheck(feature: feature, expectedResult: expectedResult)
    }
    
    func testItChangesButToAnd() {
        let scenario: Gherkin.Scenario = .simple(ScenarioSimple(name: "Scenario \\/ I want to test",
                                                        description: "",
                                                        steps:[Step(name: .given, text: "I'm in a situation"),
                                                               Step(name: .when, text: "Something happens"),
                                                               Step(name: .but, text: "Something else happens")] ))
        let feature = Feature(name: "Feature $%^& number one",
                              description: "",
                              scenarios: [scenario])
        
        let expectedResult = """
        /**
        This code is autogenerated using Capriccio 1.0.0 - https://github.com/shibapm/capriccio
        DO NOT EDIT
        */
        import XCTest
        import XCTest_Gherkin

        final class FeatureNumberOne: XCTestCase {
            func testScenarioIWantToTest() {
                Given("I'm in a situation")
                When("Something happens")
                And("Something else happens")
            }
        }
        """
        
        fileGenerationCheck(feature: feature, expectedResult: expectedResult)
    }
    
    func testItDisablesFileLenghtWarningWhenRequired() {
        let scenario: Gherkin.Scenario = .simple(ScenarioSimple(name: "Scenario \\/ I want to test",
                                                        description: "",
                                                        steps:[Step(name: .given, text: "I'm in a situation"),
                                                               Step(name: .when, text: "Something happens"),
                                                               Step(name: .but, text: "Something else happens")] ))
        let feature = Feature(name: "Feature $%^& number one",
                              description: "",
                              scenarios: [scenario])
        
        let expectedResult = """
        /**
        This code is autogenerated using Capriccio 1.0.0 - https://github.com/shibapm/capriccio
        DO NOT EDIT
        */
        import XCTest
        import XCTest_Gherkin

        // swiftlint:disable all
        final class FeatureNumberOne: XCTestCase {
            func testScenarioIWantToTest() {
                Given("I'm in a situation")
                When("Something happens")
                And("Something else happens")
            }
        }
        // swiftlint:enable all
        """
        
        fileGenerationCheck(feature: feature, expectedResult: expectedResult, disableSwiftLint: true)
    }
    
    func testItUsesAPassedTemplate() {
        let path = "testPath"
        
        try! """
        import Lib1
        import Lib2

        final class {{ feature.name }}: {{ classType }} {
        {% for scenario in feature.scenarios %}
            func testScenario_{{ scenario.name }}() {
                {% for step in scenario.steps%}
                step_{{ step.name }}(){% endfor %}
                }
            }{% endfor %}
        """.write(toFile: path, atomically: false, encoding: .utf8)
        
        let scenario: Gherkin.Scenario = .simple(ScenarioSimple(name: "Scenario \\/ I want to test",
                                                        description: "",
                                                        steps:[Step(name: .given, text: "I'm in a situation"),
                                                               Step(name: .when, text: "Something happens"),
                                                               Step(name: .but, text: "Something else happens")] ))
        let feature = Feature(name: "Feature $%^& number one",
                              description: "",
                              scenarios: [scenario])
        
        let expectedResult = """
        import Lib1
        import Lib2

        final class FeatureNumberOne: XCTestCase {
            func testScenario_ScenarioIWantToTest() {
                step_ImInASituation()
                step_SomethingHappens()
                step_SomethingElseHappens()
            }
        }
        """
        
        fileGenerationCheck(feature: feature, expectedResult: expectedResult, templateFilePath: path)
        
        try? FileManager.default.removeItem(atPath: path)
    }
    
    func fileGenerationCheck(feature: Gherkin.Feature, expectedResult: String, generatedClassType: String? = nil, templateFilePath: String? = nil, disableSwiftLint: Bool = false) {
        let text = swiftCodeGenerator.generateSwiftTestCode(forFeature: CapriccioLib.Feature(gherkinFeature: feature), generatedClassType: generatedClassType, templateFilePath: templateFilePath, disableSwiftLint: disableSwiftLint, version: "1.0.0")
        expect(self.splittedAndTrimmedStringToTest(fromString: text)) == splittedAndTrimmedStringToTest(fromString: expectedResult)
    }
    
    /// Stencil generates files with a lot of newlines and spaces depending on how is the stancil file written, given the important part to test is the actual generated text instead of the number of newlines and whitespaces, the string is splitted to take just the not empty lines and trimmed to remove the whitespaces
    private func splittedAndTrimmedStringToTest(fromString string: String) -> [String] {
        return string.split(separator: "\n", omittingEmptySubsequences: true).compactMap { let result = String($0).trim(); return result.isEmpty ? nil : result  }
    }
}

fileprivate extension String {
    func trim() -> String {
        return self.trimmingCharacters(in: NSCharacterSet.whitespaces)
    }
}
